{
    'name': "Property Management",
    'version': "18.0.1.1",
    'summary': """ An ERP for property management """,
    'description': """ A full ERP for property management """,
    'author': "Vyshnav",
    # 'depends': ['base', 'mail', 'account', 'sale'],
    'category': "Property management",
    'maintainer': "Vyshnav<vyshnav@gmail.com>",
    'sequence': 1,
    'application': True,
    'auto_install': True,
    'installable': True,
    'license': "LGPL-3",
}
