{
    'name': "Property Management",
    'version': "18.0.1.1",
    'summary': """ An ERP for property management """,
    'description': """ A full ERP for property management """,
    'author': "Vyshnav",
    'depends': ['base', 'mail', 'account', 'sale'],
    'category': "Property management",
    'maintainer': "Vyshnav<vyshnav@gmail.com>",
    'sequence': 1,
    'data': [
        "security/security_group.xml",
        "security/record.xml",
        "security/ir.model.access.csv",
        # "views/property_owner_record_view.xml",
        "views/property_management_views.xml",
        "views/rental_and_lease_management_views.xml",
        "views/property_facilities_views.xml",
        "views/property_line_view.xml",
        "views/property_management_menus.xml",
        "views/ir_sequence_data.xml",
        "data/mail.xml",
        "data/ir_crone_data.xml"
    ],
    'application': True,
    'auto_install': True,
    'installable': True,
    'license': "LGPL-3",
}
